// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWindows() {
  return window['go']['main']['App']['GetWindows']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetFocus(arg1) {
  return window['go']['main']['App']['SetFocus'](arg1);
}
