// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetWindows():Promise<Array<main.Window>>;

export function Greet(arg1:string):Promise<string>;

export function SetFocus(arg1:number):Promise<void>;
